node {
    def commit_id

    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readFile(('.git/commit-id').trim()
    }

    stage('Test') {
        nodejs(nodeJSInstallationName: 'nodejs') {
            sh 'npm install --only=dev'
            sh 'npm test'
        }
    }

    stage('Docker build/push') {
        docker.withDockerRegistry('https://index.docker.io/v1/', 'dockerhub') {
            def app = docker.build("skemuel007/nodejs-docker-jenkins:${commit_id}", '.').push();
        }
    }
}