version: '3.7'

services:
  jenkins:
    build: ./docker/slave
    restart: always
    ports:
      - 3004:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - jenkins_data_soc:/var/run/docker.sock

volumes:
  jenkins_data:
  jenkins_data_soc: