version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins
    restart: always
    ports:
      - 3004:8080
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: